name: Manage Preview Environment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'What action do you want to perform?'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - destroy

jobs:
  manage_environment:
    runs-on: ubuntu-latest
    name: Manage Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'create' }}
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: terraform
        run: terraform destroy -auto-approve

      - name: Login to Amazon ECR
        if: ${{ github.event.inputs.action == 'create' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract ECR Repository URL
        if: ${{ github.event.inputs.action == 'create' }}
        id: extract-ecr
        working-directory: terraform
        run: |
          echo "REPO_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        if: ${{ github.event.inputs.action == 'create' }}
        env:
          IMAGE_TAG: ${{ github.sha }}
          REPO_URL: ${{ env.REPO_URL }}
        run: |
          docker build -t $REPO_URL:$IMAGE_TAG -f docker/Dockerfile docker
          docker push $REPO_URL:$IMAGE_TAG
